# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readMysql', '0002_auto_20171102_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readmysql',
            options={},
        ),
        migrations.AlterModelTable(
            name='readmysql',
            table='chili',
        ),
    ]
