# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:39
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('readMysql', '0003_auto_20171102_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmysql',
            name='_json',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
