# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readMysql', '0005_auto_20171104_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='readMysql',
            new_name='Chili',
        ),
    ]
